pr: none
trigger: none

pool:
  name: 'CI'

variables:
- group: BuildVariables

jobs:
- job: Build
  timeoutInMinutes: 300
  variables:
    build.clean: all
    platform: x64
    version: 'ci'
    skipComponentGovernanceDetection: True
    validateAgainstPreviousApp: False

  steps:
  - task: PowerShell@2
    displayName: 'Run Pipeline'
    env:
      InsiderSasToken: '$(insiderSasToken)'
      Kepty_artifactType: '$(Kepty_artifactType)'
      Kepty_artifactVersion: '$(Kepty_artifactVersion)'
      Kepty_PreProcessorSymbolsCurrent: '$(Kepty_PreProcessorSymbolsCurrent)'
      Kepty_PreProcessorSymbolsNextMajor: '$(Kepty_artifaKepty_PreProcessorSymbolsNextMajorctVersion)'
      CodeSignCertPfxFile: '$(CodeSignCertPfxFile)'
      CodeSignCertPfxPassword: '$(CodeSignCertPfxPassword)'
    inputs:
      filePath: 'scripts\DevOps-Pipeline.ps1'
      arguments: '-version "$(version)" -validateAgainstPreviousApp $(validateAgainstPreviousApp)'
      warningPreference: 'stop'
      failOnStderr: true
      showWarnings: true
      
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: and(succeeded(),ne(variables['TestResults'],''))
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '$(testResults)'
      failTaskOnFailedTests: true

  - task: PowerShell@2
    displayName: 'Cleanup'
    condition: always()
    inputs:
      targetType: filePath
      filePath: 'scripts\Cleanup.ps1'
      failOnStderr: false
